CREATE TABLE ESTADO(
  IDESTADO   INT,
  ESTADO     VARCHAR(50),
  UF         VARCHAR(2),
PRIMARY KEY (IDESTADO)
);

CREATE TABLE CIDADE(
  IDCIDADE  INT,
  IDESTADO  INT,
  CIDADE    VARCHAR(80),
  CODIBGE   INT,
  UF		VARCHAR(2),
PRIMARY KEY (IDCIDADE),
FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);


CREATE TABLE ORIENTADOR (
  IDORIENTADOR    INT,
  NOME            VARCHAR(100),
  SENHA           VARCHAR(100)
PRIMARY KEY(IDORIENTADOR)
);

CREATE GENERATOR GEN_ORIENTADOR;


CREATE TRIGGER INS_ORIENTADOR FOR ORIENTADOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.IDORIENTADOR = GEN_ID(GEN_ORIENTADOR, 1);
END;

CREATE TABLE ALUNO(
  IDALUNO    INT,
  NOME       VARCHAR(100),
  SENHA      VARCHAR(100),
  IDORIENTADOR  INT,
PRIMARY KEY(IDALUNO),
FOREIGN KEY(IDORIENTADOR) REFERENCES ORIENTADOR(IDORIENTADOR)
);

CREATE GENERATOR GEN_ALUNO;


CREATE TRIGGER INS_ALUNO FOR ALUNO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.IDALUNO = GEN_ID(GEN_ALUNO, 1);
END;


CREATE TABLE PACIENTE (
  IDPACIENTE   INT,
  NOME        VARCHAR(100),
  APELIDO     VARCHAR(100),
  LOGRADOURO  VARCHAR(80),
  NUMERO      VARCHAR(10),
  BAIRRO      VARCHAR(80),
  TIPO        INT, -- 1: FÍSICA, 2: JURIDICA
  CPF_CNPJ    VARCHAR(25),
  RG_IE       VARCHAR(25),
  IDCIDADE    INT,
  IDESTADO    INT,
  TELEFONE1   VARCHAR(25),  
  TELEFONE2   VARCHAR(25),
  CELULAR     VARCHAR(25),
  SITUACAO    INT, -- 1: ATIVO, 2: INATIVO
  DATA_CAD    DATE DEFAULT CURRENT_DATE,
PRIMARY KEY(IDPACIENTE),  
FOREIGN KEY (IDCIDADE) REFERENCES CIDADE(IDCIDADE),
FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);


CREATE GENERATOR GEN_PACIENTE


CREATE TRIGGER INS_PACIENTE FOR PACIENTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  NEW.PACIENTE = GEN_ID(GEN_PACIENTE, 1);
END;