INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (1, 'ACRE', 'AC');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (2, 'ALAGOAS', 'AL');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (3, 'AMAPA', 'AP');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (4, 'AMAZONAS', 'AM');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (5, 'BAHIA', 'BA');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (6, 'CEARA', 'CE');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (7, 'DISTRITO FEDERAL', 'DF');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (8, 'ESPIRITO SANTO', 'ES');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (9, 'GOIAS', 'GO');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (10, 'MARANHAO', 'MA');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (11, 'MATO GROSSO', 'MT');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (12, 'MATO GROSSO DO SUL', 'MS');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (13, 'MINAS GERAIS', 'MG');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (14, 'PARA', 'PA');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (15, 'PARAIBA', 'PB');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (16, 'PARANA', 'PR');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (17, 'PERNAMBUCO', 'PE');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (18, 'PIAUI', 'PI');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (19, 'RIO DE JANEIRO', 'RJ');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (20, 'RIO GRANDE DO NORTE', 'RN');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (21, 'RIO GRANDE DO SUL', 'RS');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (22, 'RONDONIA', 'RO');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (23, 'RORAIMA', 'RR');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (24, 'SANTA CATARINA', 'SC');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (25, 'SAO PAULO', 'SP');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (26, 'SERGIPE', 'SE');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (27, 'TOCANTINS', 'TO');
INSERT INTO ESTADO (IDESTADO, ESTADO, UF)
            VALUES (28, 'EXTERIOR', 'EX');

COMMIT WORK;
